<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Regression | COVID dataset analyzing</title>
  <meta name="description" content="This is an analysis of a COVID dataset using different approaches." />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Regression | COVID dataset analyzing" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is an analysis of a COVID dataset using different approaches." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Regression | COVID dataset analyzing" />
  
  <meta name="twitter:description" content="This is an analysis of a COVID dataset using different approaches." />
  

<meta name="author" content="Cristina Díaz García, Beatriz Huertas Calvillo, Miguel Lillo del Barrio, María Vázquez Pendón" />


<meta name="date" content="2020-06-28" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="fcar.html"/>
<link rel="next" href="final-words.html"/>
<script src="libs/header-attrs-2.1/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.2.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.0.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.0.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.52.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.52.2/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Description</a></li>
<li class="chapter" data-level="1" data-path="visualization.html"><a href="visualization.html"><i class="fa fa-check"></i><b>1</b> Visualization</a>
<ul>
<li class="chapter" data-level="1.1" data-path="visualization.html"><a href="visualization.html#death-and-healed-calendar"><i class="fa fa-check"></i><b>1.1</b> Death and Healed Calendar</a></li>
<li class="chapter" data-level="1.2" data-path="visualization.html"><a href="visualization.html#confirmed-cases-bar-graph"><i class="fa fa-check"></i><b>1.2</b> Confirmed cases bar graph</a></li>
<li class="chapter" data-level="1.3" data-path="visualization.html"><a href="visualization.html#andalusia-bar-graphs"><i class="fa fa-check"></i><b>1.3</b> Andalusia bar graphs</a></li>
<li class="chapter" data-level="1.4" data-path="visualization.html"><a href="visualization.html#map-of-andalusia"><i class="fa fa-check"></i><b>1.4</b> Map of Andalusia</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="association-rules.html"><a href="association-rules.html"><i class="fa fa-check"></i><b>2</b> Association Rules</a></li>
<li class="chapter" data-level="3" data-path="fcar.html"><a href="fcar.html"><i class="fa fa-check"></i><b>3</b> fcaR</a></li>
<li class="chapter" data-level="4" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>4</b> Regression</a>
<ul>
<li class="chapter" data-level="4.1" data-path="regression.html"><a href="regression.html#model-of-the-number-of-infections-with-respect-to-the-date"><i class="fa fa-check"></i><b>4.1</b> Model of the number of infections with respect to the date</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="final-words.html"><a href="final-words.html"><i class="fa fa-check"></i><b>5</b> Final Words</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">COVID dataset analyzing</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regression" class="section level1" number="4">
<h1><span class="header-section-number">4</span> Regression</h1>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="regression.html#cb68-1"></a><span class="kw">library</span>(readxl)</span>
<span id="cb68-2"><a href="regression.html#cb68-2"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb68-3"><a href="regression.html#cb68-3"></a><span class="kw">library</span>(dplyr)</span>
<span id="cb68-4"><a href="regression.html#cb68-4"></a><span class="kw">library</span>(magrittr)</span>
<span id="cb68-5"><a href="regression.html#cb68-5"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb68-6"><a href="regression.html#cb68-6"></a><span class="kw">library</span>(GGally)</span></code></pre></div>
<p>We process the dataset to be able to work with it.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="regression.html#cb69-1"></a><span class="kw">colnames</span>(cs) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Fecha&quot;</span>, <span class="st">&quot;Territorio&quot;</span>, <span class="st">&quot;Confirmados_PCR&quot;</span>, <span class="st">&quot;Hospitalizados&quot;</span>, <span class="st">&quot;UCI&quot;</span>, <span class="st">&quot;Curados&quot;</span>, <span class="st">&quot;Defunciones&quot;</span>, <span class="st">&quot;Total_confirmados&quot;</span>)</span>
<span id="cb69-2"><a href="regression.html#cb69-2"></a>juntos &lt;-<span class="st"> </span></span>
<span id="cb69-3"><a href="regression.html#cb69-3"></a><span class="st">  </span><span class="kw">filter</span>(cs, cs<span class="op">$</span>Territorio <span class="op">==</span><span class="st"> &quot;Andalucía&quot;</span>)</span>
<span id="cb69-4"><a href="regression.html#cb69-4"></a>juntos &lt;-<span class="st"> </span><span class="kw">mutate</span>(juntos, <span class="dt">Total =</span> <span class="kw">cumsum</span>(Total_confirmados))</span>
<span id="cb69-5"><a href="regression.html#cb69-5"></a>                        </span>
<span id="cb69-6"><a href="regression.html#cb69-6"></a>                        </span>
<span id="cb69-7"><a href="regression.html#cb69-7"></a>c &lt;-<span class="st"> </span>juntos<span class="op">$</span>Curados</span>
<span id="cb69-8"><a href="regression.html#cb69-8"></a>h &lt;-<span class="st"> </span>juntos<span class="op">$</span>Hospitalizados</span>
<span id="cb69-9"><a href="regression.html#cb69-9"></a>d &lt;-<span class="st"> </span>juntos<span class="op">$</span>Defunciones</span>
<span id="cb69-10"><a href="regression.html#cb69-10"></a>uci &lt;-<span class="st"> </span>juntos<span class="op">$</span>UCI</span>
<span id="cb69-11"><a href="regression.html#cb69-11"></a>conf &lt;-<span class="st"> </span>juntos<span class="op">$</span>Confirmados_PCR</span>
<span id="cb69-12"><a href="regression.html#cb69-12"></a>totalconf &lt;-<span class="st"> </span>juntos<span class="op">$</span>Total_confirmados</span>
<span id="cb69-13"><a href="regression.html#cb69-13"></a>salidac &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="st">&quot;numeric&quot;</span>,<span class="kw">length</span>(c))</span>
<span id="cb69-14"><a href="regression.html#cb69-14"></a>salidah &lt;-<span class="kw">vector</span>(<span class="st">&quot;numeric&quot;</span>,<span class="kw">length</span>(h))</span>
<span id="cb69-15"><a href="regression.html#cb69-15"></a>salidad &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="st">&quot;numeric&quot;</span>,<span class="kw">length</span>(d))</span>
<span id="cb69-16"><a href="regression.html#cb69-16"></a>salidauci &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="st">&quot;numeric&quot;</span>,<span class="kw">length</span>(uci))</span>
<span id="cb69-17"><a href="regression.html#cb69-17"></a>salidaconf &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="st">&quot;numeric&quot;</span>,<span class="kw">length</span>(conf))</span>
<span id="cb69-18"><a href="regression.html#cb69-18"></a>salidatotalconf &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="st">&quot;numeric&quot;</span>,<span class="kw">length</span>(totalconf))</span>
<span id="cb69-19"><a href="regression.html#cb69-19"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="kw">seq_along</span>(c)){</span>
<span id="cb69-20"><a href="regression.html#cb69-20"></a>  </span>
<span id="cb69-21"><a href="regression.html#cb69-21"></a>  salidac[<span class="kw">length</span>(c)<span class="op">+</span><span class="dv">1</span><span class="op">-</span>i] &lt;-<span class="st"> </span>c[i]</span>
<span id="cb69-22"><a href="regression.html#cb69-22"></a>  salidah[<span class="kw">length</span>(h)<span class="op">+</span><span class="dv">1</span><span class="op">-</span>i] &lt;-<span class="st"> </span>h[i]</span>
<span id="cb69-23"><a href="regression.html#cb69-23"></a>  salidad[<span class="kw">length</span>(d)<span class="op">+</span><span class="dv">1</span><span class="op">-</span>i] &lt;-<span class="st"> </span>d[i]</span>
<span id="cb69-24"><a href="regression.html#cb69-24"></a>  salidauci[<span class="kw">length</span>(uci)<span class="op">+</span><span class="dv">1</span><span class="op">-</span>i] &lt;-<span class="st"> </span>uci[i]</span>
<span id="cb69-25"><a href="regression.html#cb69-25"></a>  salidaconf[<span class="kw">length</span>(conf)<span class="op">+</span><span class="dv">1</span><span class="op">-</span>i] &lt;-<span class="st"> </span>conf[i]</span>
<span id="cb69-26"><a href="regression.html#cb69-26"></a>  salidatotalconf[<span class="kw">length</span>(totalconf)<span class="op">+</span><span class="dv">1</span><span class="op">-</span>i] &lt;-<span class="st"> </span>totalconf[i]</span>
<span id="cb69-27"><a href="regression.html#cb69-27"></a>  </span>
<span id="cb69-28"><a href="regression.html#cb69-28"></a>}</span>
<span id="cb69-29"><a href="regression.html#cb69-29"></a>juntos<span class="op">$</span>Curados &lt;-<span class="st"> </span>salidac</span>
<span id="cb69-30"><a href="regression.html#cb69-30"></a>juntos<span class="op">$</span>Hospitalizados &lt;-<span class="st"> </span>salidah</span>
<span id="cb69-31"><a href="regression.html#cb69-31"></a>juntos<span class="op">$</span>Defunciones &lt;-<span class="st"> </span>salidad</span>
<span id="cb69-32"><a href="regression.html#cb69-32"></a>juntos<span class="op">$</span>UCI &lt;-<span class="st"> </span>salidauci</span>
<span id="cb69-33"><a href="regression.html#cb69-33"></a>juntos<span class="op">$</span>Confirmados_PCR &lt;-<span class="st"> </span>salidaconf</span>
<span id="cb69-34"><a href="regression.html#cb69-34"></a>juntos<span class="op">$</span>Total_confirmados &lt;-<span class="st"> </span>salidatotalconf</span>
<span id="cb69-35"><a href="regression.html#cb69-35"></a>                     </span>
<span id="cb69-36"><a href="regression.html#cb69-36"></a>  fechas &lt;-<span class="st"> </span><span class="kw">as.Date</span>(juntos<span class="op">$</span>Fecha ,<span class="st">&quot;%d/%m/%Y&quot;</span>)</span>
<span id="cb69-37"><a href="regression.html#cb69-37"></a>juntos<span class="op">$</span>Fecha &lt;-<span class="st"> </span><span class="kw">sort</span>(fechas)                      </span></code></pre></div>
<p>We make the graph of how the cases have increased as a function of time.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="regression.html#cb70-1"></a><span class="kw">attach</span>(juntos)</span>
<span id="cb70-2"><a href="regression.html#cb70-2"></a>grafica &lt;-<span class="st"> </span>juntos <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span> Fecha, <span class="dt">y=</span> Total))<span class="op">+</span><span class="kw">geom_point</span>()</span>
<span id="cb70-3"><a href="regression.html#cb70-3"></a>grafica</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>In this graph we can see how the number of cases up to May increased exponentially. However, starting from this date, the number of cases per day begins to decrease, reaching the famous peak.</p>
<div id="model-of-the-number-of-infections-with-respect-to-the-date" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Model of the number of infections with respect to the date</h2>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="regression.html#cb71-1"></a>modFC &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">formula =</span> juntos<span class="op">$</span>Total <span class="op">~</span><span class="st"> </span>juntos<span class="op">$</span>Fecha, <span class="dt">data =</span> juntos)</span>
<span id="cb71-2"><a href="regression.html#cb71-2"></a>modFC</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = juntos$Total ~ juntos$Fecha, data = juntos)
## 
## Coefficients:
##  (Intercept)  juntos$Fecha  
##   -4444803.2         242.5</code></pre>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="regression.html#cb73-1"></a><span class="kw">summary</span>(modFC)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = juntos$Total ~ juntos$Fecha, data = juntos)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2038.5 -1147.8  -133.7  1165.0  2423.5 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -4.445e+06  1.110e+05  -40.03   &lt;2e-16 ***
## juntos$Fecha  2.425e+02  6.047e+00   40.11   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1420 on 85 degrees of freedom
## Multiple R-squared:  0.9498, Adjusted R-squared:  0.9492 
## F-statistic:  1609 on 1 and 85 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>We start by checking if there is a model, for this we look at the values of F-statistic and p-value.
** F-statistic ** is quite far from 1 (1609), so it indicates that there is a model.
** P-value **, is well below 0.005, confirming that there is a model (H1 is met)
Now that we know there is a model, let’s study how good our model is.</p>
<p>We look at <span class="math inline">\(R^2\)</span>, which has a value of 0.9498, a pretty good value, since <strong>94.98%</strong> of the cases are collected with this model.
We also see that there is almost no difference between adjusted <span class="math inline">\(R^2\)</span> and <span class="math inline">\(R^2\)</span>, so <em>there is no overfitting</em> in our model and that the values are relevant (indicated by ***)
Let’s continue studying the model, for this we will see the graphs of the adjusted values and residuals.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="regression.html#cb75-1"></a><span class="kw">plot</span>(modFC)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-18-1.png" width="672" /><img src="bookdown-demo_files/figure-html/unnamed-chunk-18-2.png" width="672" /><img src="bookdown-demo_files/figure-html/unnamed-chunk-18-3.png" width="672" /><img src="bookdown-demo_files/figure-html/unnamed-chunk-18-4.png" width="672" /></p>
<p>In these graphs we can see how it begins adjusting to the values. However, as cases increase, there is more waste.
This may be due to the results of the contingency measures that were taken.
With all this we could say that we have a pretty good model.
## Model of the number of people who were hospitalized with respect to the number of infected.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="regression.html#cb76-1"></a>mHospitalizados &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">formula =</span> Hospitalizados <span class="op">~</span><span class="st"> </span>Total_confirmados, <span class="dt">data =</span> juntos)</span>
<span id="cb76-2"><a href="regression.html#cb76-2"></a>mHospitalizados</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Hospitalizados ~ Total_confirmados, data = juntos)
## 
## Coefficients:
##       (Intercept)  Total_confirmados  
##          -31.5285             0.5212</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="regression.html#cb78-1"></a><span class="kw">summary</span>(mHospitalizados)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Hospitalizados ~ Total_confirmados, data = juntos)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -98.696 -24.055   4.173  29.359  84.144 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       -31.52846    5.98438  -5.268 1.02e-06 ***
## Total_confirmados   0.52117    0.02246  23.200  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 37.37 on 85 degrees of freedom
## Multiple R-squared:  0.8636, Adjusted R-squared:  0.862 
## F-statistic: 538.3 on 1 and 85 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>We start by checking if there is a model, for this we look at the values of F-statistic and p-value.
F-statistic is quite far from 1 (538), so it indicates that there is a model.
P-value, is well below 0.005, which confirms that there is a model (H1 is met)
Now that we know there is a model, let’s study how good our model is.
We look at <span class="math inline">\(R^2\)</span>, which has a value of 0.8636, a pretty good value, since 86.36% of hospitalization cases are included in this model.
We also see that there is almost no difference between adjusted <span class="math inline">\(R^2\)</span> and <span class="math inline">\(R^2\)</span>, so there is no overfitting in our model and that the values are relevant (indicated by ***)
Let’s continue studying the model, for this we will see the graphs of the adjusted values and residuals.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="regression.html#cb80-1"></a><span class="kw">plot</span>(mHospitalizados)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-21-1.png" width="672" /><img src="bookdown-demo_files/figure-html/unnamed-chunk-21-2.png" width="672" /><img src="bookdown-demo_files/figure-html/unnamed-chunk-21-3.png" width="672" /><img src="bookdown-demo_files/figure-html/unnamed-chunk-21-4.png" width="672" /></p>
<p>In the graphs we can see how there is dispersion of the values, and how it fits better at the beginning than at the end.
We also observed that at the beginning of the period the number of hospitalized was very close to the number of cases. But as time progresses, the number of cases increases considerably, but not so much the number of hospitalized. This may be due to the fact that the population was informed of the first symptoms and the measures they had to take, so that an infected person could be detected in the early stages and monitored so that the severity could be reduced.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="regression.html#cb81-1"></a><span class="kw">library</span>(readxl)</span>
<span id="cb81-2"><a href="regression.html#cb81-2"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb81-3"><a href="regression.html#cb81-3"></a>datos &lt;-<span class="st"> </span><span class="kw">read_excel</span>(<span class="st">&quot;cs_export.xls&quot;</span>)</span>
<span id="cb81-4"><a href="regression.html#cb81-4"></a>datos &lt;-<span class="st"> </span><span class="kw">na.omit</span>(datos)</span>
<span id="cb81-5"><a href="regression.html#cb81-5"></a><span class="kw">names</span>(datos) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">names</span>(datos[<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>]),<span class="st">&quot;Confirmados_PCR&quot;</span>,<span class="kw">names</span>(datos[<span class="dv">4</span><span class="op">:</span><span class="dv">7</span>]),<span class="st">&quot;Total_confirmados&quot;</span>)</span>
<span id="cb81-6"><a href="regression.html#cb81-6"></a>varPred &lt;-<span class="st"> </span><span class="kw">names</span>(datos[<span class="kw">c</span>(<span class="dv">3</span><span class="op">:</span><span class="dv">6</span>,<span class="dv">8</span>)])</span>
<span id="cb81-7"><a href="regression.html#cb81-7"></a>datos<span class="op">$</span><span class="st">`</span><span class="dt">Fecha declaración</span><span class="st">`</span> &lt;-<span class="st"> </span><span class="kw">as.Date</span>(datos<span class="op">$</span><span class="st">`</span><span class="dt">Fecha declaración</span><span class="st">`</span>, <span class="st">&quot;%d/%m/%Y&quot;</span>)</span>
<span id="cb81-8"><a href="regression.html#cb81-8"></a>datos &lt;-<span class="st"> </span><span class="kw">arrange</span>(datos, <span class="st">`</span><span class="dt">Fecha declaración</span><span class="st">`</span>)</span>
<span id="cb81-9"><a href="regression.html#cb81-9"></a>filasandalucia &lt;-<span class="st"> </span><span class="kw">filter</span>(datos, Territorio<span class="op">==</span><span class="st">&quot;Andalucía&quot;</span> )</span></code></pre></div>
<p>We are going to produce a multivariate regression model that explains the variable <em>Defunction</em> using an iterative technique in which we will add each time the variable whose R-adjusted is greater.</p>
<p>We define a function to calculate the linear model of a sum of variables</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="regression.html#cb82-1"></a>linearAdjust &lt;-<span class="st"> </span><span class="cf">function</span>(df, y, x){</span>
<span id="cb82-2"><a href="regression.html#cb82-2"></a>  mod1 &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="kw">str_c</span>(y,<span class="st">&quot;~&quot;</span>,<span class="kw">str_c</span>(x,<span class="dt">collapse=</span><span class="st">&quot;+&quot;</span>)),df)</span>
<span id="cb82-3"><a href="regression.html#cb82-3"></a>}</span>
<span id="cb82-4"><a href="regression.html#cb82-4"></a>calcModR2 &lt;-<span class="st"> </span><span class="cf">function</span>(df,y,x){</span>
<span id="cb82-5"><a href="regression.html#cb82-5"></a>  mod &lt;-<span class="st"> </span><span class="kw">linearAdjust</span>(df,y,x)</span>
<span id="cb82-6"><a href="regression.html#cb82-6"></a>  <span class="kw">summary</span>(mod)<span class="op">$</span>adj.r.squared</span>
<span id="cb82-7"><a href="regression.html#cb82-7"></a>}</span></code></pre></div>
<p>We are adding variables while increasing the value of adjusted <span class="math inline">\(R^2\)</span>.</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="regression.html#cb83-1"></a>encontrarMejorAjuste &lt;-<span class="st"> </span><span class="cf">function</span>(df,varPos){</span>
<span id="cb83-2"><a href="regression.html#cb83-2"></a>  bestVars &lt;-<span class="st"> </span><span class="kw">character</span>(<span class="dv">0</span>)</span>
<span id="cb83-3"><a href="regression.html#cb83-3"></a>  aR2 &lt;-<span class="st"> </span><span class="dv">0</span></span>
<span id="cb83-4"><a href="regression.html#cb83-4"></a>  <span class="cf">repeat</span>{</span>
<span id="cb83-5"><a href="regression.html#cb83-5"></a>    aR2v &lt;-<span class="st"> </span><span class="kw">map_dbl</span>(varPos,<span class="op">~</span><span class="kw">calcModR2</span>(df, <span class="st">&quot;Defunciones&quot;</span>,<span class="kw">c</span>(bestVars,.)))</span>
<span id="cb83-6"><a href="regression.html#cb83-6"></a>    i    &lt;-<span class="st"> </span><span class="kw">which.max</span>(aR2v)</span>
<span id="cb83-7"><a href="regression.html#cb83-7"></a>    aR2M &lt;-<span class="st"> </span>aR2v[i]</span>
<span id="cb83-8"><a href="regression.html#cb83-8"></a>    </span>
<span id="cb83-9"><a href="regression.html#cb83-9"></a>    <span class="cf">if</span>(aR2M<span class="op">&lt;=</span>aR2 <span class="op">||</span><span class="kw">length</span>(varPos)<span class="op">&lt;</span><span class="dv">1</span>) <span class="cf">break</span></span>
<span id="cb83-10"><a href="regression.html#cb83-10"></a>    <span class="co">#Valor del r-ajustado añadido y nombre de la variable elegida</span></span>
<span id="cb83-11"><a href="regression.html#cb83-11"></a>    <span class="kw">cat</span>(<span class="kw">sprintf</span>(<span class="st">&quot;%1.4f %s</span><span class="ch">\n</span><span class="st">&quot;</span>,aR2M,varPos[i]))</span>
<span id="cb83-12"><a href="regression.html#cb83-12"></a>    aR2 &lt;-<span class="st"> </span>aR2M</span>
<span id="cb83-13"><a href="regression.html#cb83-13"></a>    bestVars &lt;-<span class="st"> </span><span class="kw">c</span>(bestVars,varPos[i])</span>
<span id="cb83-14"><a href="regression.html#cb83-14"></a>    varPos &lt;-<span class="st"> </span>varPos[<span class="op">-</span>i]</span>
<span id="cb83-15"><a href="regression.html#cb83-15"></a>  }</span>
<span id="cb83-16"><a href="regression.html#cb83-16"></a>  mod &lt;-<span class="st"> </span><span class="kw">linearAdjust</span>(df,<span class="st">&quot;Defunciones&quot;</span>,bestVars)</span>
<span id="cb83-17"><a href="regression.html#cb83-17"></a>  <span class="kw">list</span>(<span class="dt">vars=</span>bestVars,<span class="dt">mod=</span>mod)</span>
<span id="cb83-18"><a href="regression.html#cb83-18"></a>}</span>
<span id="cb83-19"><a href="regression.html#cb83-19"></a>bestMod &lt;-<span class="st"> </span><span class="kw">encontrarMejorAjuste</span>(filasandalucia, varPred)</span></code></pre></div>
<pre><code>## 0.9499 Hospitalizados
## 0.9521 UCI
## 0.9530 Curados
## 0.9566 Total_confirmados
## 0.9642 Confirmados_PCR</code></pre>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="regression.html#cb85-1"></a>bestMod</span></code></pre></div>
<pre><code>## $vars
## [1] &quot;Hospitalizados&quot;    &quot;UCI&quot;               &quot;Curados&quot;          
## [4] &quot;Total_confirmados&quot; &quot;Confirmados_PCR&quot;  
## 
## $mod
## 
## Call:
## lm(formula = str_c(y, &quot;~&quot;, str_c(x, collapse = &quot;+&quot;)), data = df)
## 
## Coefficients:
##       (Intercept)     Hospitalizados                UCI            Curados  
##           0.26562            0.11219            0.35878           -0.21053  
## Total_confirmados    Confirmados_PCR  
##           0.10853            0.08473</code></pre>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="regression.html#cb87-1"></a><span class="kw">summary</span>(bestMod<span class="op">$</span>mod)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = str_c(y, &quot;~&quot;, str_c(x, collapse = &quot;+&quot;)), data = df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -11.2602  -2.2208  -0.3433   1.8867  13.9259 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        0.26562    0.82376   0.322 0.747941    
## Hospitalizados     0.11219    0.03151   3.561 0.000623 ***
## UCI                0.35878    0.10317   3.478 0.000816 ***
## Curados           -0.21053    0.03937  -5.347 8.07e-07 ***
## Total_confirmados  0.10853    0.02412   4.499 2.26e-05 ***
## Confirmados_PCR    0.08473    0.01978   4.284 5.02e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.285 on 81 degrees of freedom
## Multiple R-squared:  0.9663, Adjusted R-squared:  0.9642 
## F-statistic: 463.9 on 5 and 81 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The model obtained would be of the form:</p>
<p><span class="math display">\[
Defunciones=0.2656235 +0.1121855·Hospitalizados+0.3587845·UCI+-0.2105297·ConfirmadosPCR+0.1085301·Curados+0.0847283·TotalConfirmados
\]</span></p>
<p>Finally we can represent the graph of the data (purple) with the regression obtained superimposed (red)</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="regression.html#cb89-1"></a>g &lt;-<span class="st"> </span><span class="kw">ggplot</span>(filasandalucia, <span class="kw">aes</span>(<span class="dt">x=</span><span class="st">`</span><span class="dt">Fecha declaración</span><span class="st">`</span>,<span class="dt">y=</span>Defunciones))<span class="op">+</span></span>
<span id="cb89-2"><a href="regression.html#cb89-2"></a><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;Regresión multilineal&quot;</span>)<span class="op">+</span></span>
<span id="cb89-3"><a href="regression.html#cb89-3"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">colour=</span><span class="st">&quot;purple&quot;</span>)<span class="op">+</span></span>
<span id="cb89-4"><a href="regression.html#cb89-4"></a><span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="st">`</span><span class="dt">Fecha declaración</span><span class="st">`</span>, <span class="kw">predict.lm</span>(bestMod<span class="op">$</span>mod)), <span class="dt">color=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb89-5"><a href="regression.html#cb89-5"></a>  </span>
<span id="cb89-6"><a href="regression.html#cb89-6"></a>g</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="fcar.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="final-words.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/04_Regression.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
